service: sls-web-template
frameworkVersion: '3'
custom:
  events: ${file(./customConfig.yml):myevents}
  defaultStage: dev
  # serverless-python-requirements: https://www.serverless.com/plugins/serverless-python-requirements
  # NOTE: requirements.txtはserverless.ymlと同じディレクトリに配置する必要がある
  # TODO: Layerを別プロジェクトに分ける: https://blog.ikedaosushi.com/entry/2019/04/07/012612
  pythonRequirements:
    dockerizePip: true # deploy時のパッケージングの際にpythonライブラリのビルドをdockerで行う設定
    layer: true # レイヤーを作成する

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    APP_NAME: sls-web-template

# デプロイパッケージに含めるファイル/ディレクトリを指定
package:
  patterns:
    - '!**' # すべてのファイルをexclude
    - 'api/**' # apiディレクトリは以下をinclude

functions:
  api:
    handler: api.main.handler
    role: ApiRole
    events:
      - http:
          path: /{path+}
          method: ANY
          private: false
          cors: true
    environment:
      STAGE: ${opt:stage, self:custom.defaultStage}
      SECRET_KEY: ${env:SECRET_KEY}
    layers:
      - Ref: PythonRequirementsLambdaLayer

# you can add CloudFormation resource templates here
resources:
  Resources:
    ApiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: slsWebTemplate-apiRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole 
        Policies:
          - PolicyName: apiAppPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Resource: "*"
                  Effect: Allow
                  Action:
                    - "s3:*"
                - Resource: "*"
                  Effect: Allow
                  Action:
                    - "dynamodb:*"
                    - "dax:*"

plugins:
  - serverless-python-requirements
