service: sls-web-template
frameworkVersion: '3'
custom:
  profile: ${file(./profile/${opt:stage}.yml)}
  # serverless-python-requirements: https://www.serverless.com/plugins/serverless-python-requirements
  # NOTE: requirements.txtはserverless.ymlと同じディレクトリに配置する必要がある
  # TODO: Layerを別プロジェクトに分ける: https://blog.ikedaosushi.com/entry/2019/04/07/012612
  pythonRequirements:
    dockerizePip: true # deploy時のパッケージングの際にpythonライブラリのビルドをdockerで行う設定
    layer: true # レイヤーを作成する

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.profile.stage, "dev"}
  profile: ${self:custom.profile.awsProfile}
  region: ${self:custom.profile.awsRegion}
  deploymentBucket: ${self:custom.profile.deploymentBucket}
  vpc:
    securityGroupIds: ${self:custom.profile.securityGroupIds}
    subnetIds: ${self:custom.profile.subnetIds}
  environment:
    APP_NAME: ${self:service}
    STAGE: ${self:provider.stage}
  # APIGatewayでプライベートAPIを作成する
  # https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/apigateway-private-apis.html
  # Endpoint Type: https://www.serverless.com/framework/docs/providers/aws/events/apigateway#configuring-endpoint-types
  endpointType: PRIVATE
  vpcEndpointIds: 
    - ${self:custom.profile.vpcEndpointId}
  # VPCエンドポイント経由のリクエストのみを許可する設定
  # ResourcePolicy: https://www.serverless.com/framework/docs/providers/aws/events/apigateway#resource-policy
  apiGateway:
    resourcePolicy:
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*
        Condition:
          StringNotEquals:
            aws:sourceVpce: ${self:custom.profile.vpcEndpointId}
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource: "execute-api:/*"

# デプロイパッケージに含めるファイル/ディレクトリを指定
package:
  patterns:
    - '!**' # すべてのファイルをexclude
    - 'api/**' # fastapiのソースコードをinclude
    - 'front_dist/**' # nuxtのビルド青果物をinclude

functions:
  api:
    handler: api.main.handler
    timeout: 29
    role: ApiRole
    events:
      - http:
          path: /
          method: ANY
          private: false
          cors: true
      - http:
          path: /{path+}
          method: ANY
          private: false
          cors: true
    environment: ${self:custom.profile.apienv}
    layers:
      - Ref: PythonRequirementsLambdaLayer

# you can add CloudFormation resource templates here
resources:
  Resources:
    ApiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: slsWebTemplate-apiRole-${self:provider.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole 
        Policies:
          - PolicyName: apiAppPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Resource: "*"
                  Effect: Allow
                  Action:
                    - "s3:*"
                - Resource: "*"
                  Effect: Allow
                  Action:
                    - "dynamodb:*"
                    - "dax:*"

plugins:
  - serverless-python-requirements
