---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/api:latest
    container_name: api
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}/api"
        target: "/opt/app/api"
      - type: bind
        source: "${PROJECT_ROOT}/front_dist"
        target: "/opt/app/front_dist"
    command: /usr/local/bin/api-entrypoint.sh
    env_file:
      - "${ENV_PATH}"
    network_mode: host
  front:
    image: ${APP_NAME}/front:latest
    container_name: front
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}/front"
        target: "/opt/app/front"
    command: /usr/local/bin/front-entrypoint.sh
    network_mode: host