---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/api:latest
    container_name: api
    env_file:
      - "${ENV_PATH}"
    network_mode: host
  nginx:
    image: ${APP_NAME}/nginx:latest
    container_name: nginx
    depends_on:
      - api
    network_mode: host