---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/dev:latest
    container_name: api
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}"
        target: "/opt/app"
    command: /opt/app/docker/dev/api-entrypoint.sh
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    env_file:
      - "${ENV_PATH}"
    network_mode: host
  front:
    image: ${APP_NAME}/dev:latest
    container_name: front
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}"
        target: "/opt/app"
    command: /opt/app/docker/dev/front-entrypoint.sh
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    network_mode: host